project:
  type: website

website:
  title: "Joey Lee"
  page-navigation: true
  site-url: /
  navbar:
    left:
      - index.qmd
      - projects.qmd
      - courses.qmd


format:
  html:
    theme:
      - default
      - brand
    css: styles.css
    toc: true

editor: visual

